# Generated by Django 3.2.23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_booksearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='PDFDrive.com link as fallback', null=True),
        ),
    ] 
